---
- name: Remove old mount configuration from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "{{ item }}"
    state: absent
  with_items:
    - ROSBAG
    - LOG
  become: yes

- name: Add tmpfs entry to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "tmpfs /media/autoware/LOG tmpfs rw,nosuid,nodev,noexec,nofail,size=10G,mode=1755 0 0"
    state: present
    create: yes
  become: yes

- name: Add exteral storage entry to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "LABEL=ROSBAG /media/autoware/ROSBAG ext4 nofail 0 0"
    state: present
    create: yes
  become: yes
