---
- hosts: localhost
  vars_files:
    - ./vars/mysetting.yml
  roles:
    - { role: apt-install, tags: ["apt-install"] }
    - { role: git-config, tags: ["git-config"] }
    - { role: vscode, tags: ["vscode"] }
