---
- hosts: localhost
  vars_files:
    - ./vars/main.yml
  become: no
  roles:
    - { role: common, tags: ["common"] }
    # - { role: git-config, tags: ["git-config"] }
    # - { role: vscode, tags: ["vscode"] }
    # - { role: ros, rosdistro: noetic, tags: ["ros"] }
    - { role: ros2, tags: ["ros2"] }
    # - { role: docker, tags: ["docker"] }
