---
- hosts: localhost
  vars_files:
    - ./vars/mysetting.yml
  roles:
    - { role: common, tags: ["common"] }
    - { role: git-config, tags: ["git-config"] }
    - { role: vscode, tags: ["vscode"] }
