---
- name: Install dependencies
  apt:
    name:
      - alsa-base
      - alsa-utils
    update_cache: yes
  become: yes

- name: Copy script
  copy:
    src: setup.sh
    dest: /opt/autoware/services/mixer-setup/
    mode: 0755
  become: yes

- name: Install service
  copy:
    src: mixer-setup.service
    dest: "/etc/systemd/system"
    mode: "0644"
  become: yes

- name: insert sound card device order setting (for ADLink)
  lineinfile:
    path: "/etc/modprobe.d/alsa-base.conf"
    line: "{{ item }}"
  with_items:
    - "# to enable intel soundcard as default"
    - "options snd-hda-intel index=0,1 vid=8086,10de"
  become: yes

- name: Enable service
  systemd:
    name: mixer-setup.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
