---
- name: Install ptp4l
  apt:
    name:
      - linuxptp
    update_cache: yes
  become: yes

- name: Copy service
  ansible.builtin.copy:
    src: ptp4l@.service
    dest: /etc/systemd/system/
    mode: 0755
  become: yes

- name: Enable service enp3s0
  ansible.builtin.systemd:
    name: ptp4l@enp3s0.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes

- name: Enable service enp4s0
  ansible.builtin.systemd:
    name: ptp4l@enp4s0.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
