---
- name: Install GPIO packages
  apt:
    name:
      - libgpiod2
      - libgpiod-dev
      - libgpiod-doc
      - gpiod
    state: latest
    update_cache: yes
  become: yes

- name: Create new group named gpio
  group:
    name: "{{ gpio_group_name }}"
    gid: "{{  gpio_gid }}"
  become: yes

- name: Add autoware user to gpio group
  user:
    name: "{{ autoware_user_name }}"
    append: yes
    groups: "{{ gpio_group_name }}"
    uid: "{% if lookup('env', 'GITHUB_ACTIONS') != 'true' %}{{autoware_user_uid}}{% else %}{{omit}}{% endif %}"
  become: yes

- name: Create a new rule file for GPIO permission
  file:
    path: "{{ gpiod_permission_udev_path }}"
    state: touch
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    follow: no
  become: yes

- name: Add rule statement to the created file
  lineinfile:
    path: "{{ gpiod_permission_udev_path }}"
    line: SUBSYSTEM=="gpio",KERNEL=="gpiochip*", ACTION=="add", PROGRAM="/bin/sh -c 'chown root:gpio /dev/gpiochip* && chmod g+rw /dev/gpiochip*'"
    insertafter: EOF
  become: yes
