---
- name: Install ptpd
  apt:
    name:
      - ptpd
    update_cache: yes
  become: yes

- name: Copy service
  ansible.builtin.copy:
    src: ptpd.service
    dest: /etc/systemd/system/
    mode: 0755
  become: yes

- name: Enable service
  ansible.builtin.systemd:
    name: ptpd.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
