---
- name: Install chrony
  apt:
    name:
      - chrony
    update_cache: yes
  become: yes

- name: Enable service
  ansible.builtin.systemd:
    name: chrony.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes

- name: Add settings to /etc/chrony/chrony.conf
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - "leapsecmode slew"
    - "maxslewrate {{ maxslewrate }}"
    - "smoothtime {{ smoothtime }}"
  become: yes

- name: Remove settings from /etc/chrony/chrony.conf
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: "^makestep"
    line: "makestep 0 1"
  become: yes
