---
- name: Install dependencies
  apt:
    name:
      - python3-pip
      - jq
    update_cache: yes
  become: yes

- name: Clone OTA Client
  git:
    repo: "{{ ota_client_repository_url }}"
    dest: "{{ ota_client_clone_dir }}"
    version: "{{ ota_client_version }}"

- name: Install python requirements
  pip:
    requirements: "{{ ota_client_clone_dir }}/app/requirements.txt"
    executable: pip3
  become: yes

- name: Create OTA Client directory
  file:
    path: "{{ ota_client_install_dir }}"
    state: directory
    mode: "0755"
    owner: root
  become: yes

- name: Create OTA Boot directory
  file:
    path: "{{ ota_client_boot_dir }}"
    state: directory
    mode: "0755"
    owner: root
  become: yes

- name: Install OTA Client app
  copy:
    src: "{{ ota_client_clone_dir }}/app"
    dest: "{{ ota_client_install_dir }}"
    mode: "0644"
  become: yes

- name: Install OTA Client systemd
  copy:
    src: "{{ ota_client_clone_dir }}/systemd/"
    dest: "/etc/systemd/system"
    mode: "0644"
  become: yes

- name: Install OTA Boot files
  copy:
    src: "{{ ota_client_clone_dir }}/boot/ota/"
    dest: "{{ ota_client_boot_dir }}"
    mode: "0644"
  become: yes

- name: Enable service
  systemd:
    name: otaclient.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes

- name: Create OTA Client bin directory
  file:
    path: "{{ ota_client_install_dir }}/bin"
    state: directory
    mode: "0755"
    owner: root
  become: yes

- name: Install AWS greengrass log config script
  copy:
    src: "bin/config-aws_gglog.sh"
    dest: "{{ ota_client_install_dir }}/bin/"
    owner: root
    mode: "0755"
  become: yes

- name: Create OTA Client systemd otaclient.service dicretocy
  file:
    path: "/etc/systemd/system/otaclient.service.d"
    state: directory
    mode: "0755"
    owner: root
  become: yes

- name: Install OTA Client systemd aws greengrass log config
  template:
    src: "systemd/aws_gglog.conf.j2"
    dest: "/etc/systemd/system/otaclient.service.d/aws_gglog.conf"
    owner: root
    mode: "0644"
  become: yes

- name: Install OTA Client Config systemd service file
  template:
    src: "systemd/otaclient-config.service.j2"
    dest: "/etc/systemd/system/otaclient-config.service"
    owner: root
    mode: "0644"
  become: yes

- name: Enable OTA Client Config service
  systemd:
    name: otaclient-config.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
