---
- name: Copy script
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/autoware/services/peak-can-pci-interface/
    mode: 0755
  with_items:
    - can-up.sh
    - can-down.sh
  become: yes

- name: Copy service
  ansible.builtin.copy:
    src: peak-can-pci-interface.service
    dest: /etc/systemd/system/
    mode: 0755
  become: yes

- name: Enable service
  ansible.builtin.systemd:
    name: peak-can-pci-interface.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
