---
- name: Copy config
  ansible.builtin.copy:
    src: cyclonedds-local.xml
    dest: /opt/autoware/services/cyclonedds-local/
    mode: 0755
  become: yes

- name: Add settings to autoware.env
  ansible.builtin.lineinfile:
    path: ~/autoware.env
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - export CYCLONEDDS_URI=file:///opt/autoware/services/cyclonedds-local/cyclonedds-local.xml
  become: no

- name: Copy script
  ansible.builtin.copy:
    src: setup.sh
    dest: /opt/autoware/services/cyclonedds-local/
    mode: 0755
  become: yes

- name: Copy service
  ansible.builtin.copy:
    src: cyclonedds-local.service
    dest: /etc/systemd/system/
    mode: 0755
  become: yes

- name: Enable service
  ansible.builtin.systemd:
    name: cyclonedds-local.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
