---
- name: Add vehicle_id to vehicle.env
  ansible.builtin.lineinfile:
    path: ~/vehicle.env
    line: "export VEHICLE_ID={{ vehicle_id }}"
    state: present
    create: yes
  become: no

- name: Add vehicle_model to vehicle.env
  ansible.builtin.lineinfile:
    path: ~/vehicle.env
    line: "export VEHICLE_MODEL={{ vehicle_model }}"
    state: present
    create: yes
  become: no

- name: Add settings to autoware.env
  ansible.builtin.lineinfile:
    path: ~/autoware.env
    line: "{{ item }}"
    state: present
    create: yes
  with_items:
    - "source {{ autoware_install_dir }}/install/setup.bash"
    - "export ROS_DOMAIN_ID={{ ros_domain_id }}"
  become: no

- name: Add settings to .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
    state: present
  become: no
  with_items:
    - source ~/autoware.env
    - source ~/vehicle.env

- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/autoware/services/autoware-launch/
    mode: 0755
  with_items:
    - setup.sh
    - run.sh
  become: yes

- name: Copy service
  ansible.builtin.copy:
    src: autoware-launch.service
    dest: /etc/systemd/system/
    mode: 0755
  become: yes

- name: Enable service
  ansible.builtin.systemd:
    name: autoware-launch.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
