---
- name: Install dependencies
  apt:
    name:
      - python3-pip
    update_cache: yes
  become: yes

- name: Clone ota-internal
  git:
    repo: "{{ ota_internal_repository_url }}"
    dest: "{{ ota_internal_clone_dir }}"

- name: Install python requirements
  pip:
    requirements: "{{ ota_internal_clone_dir }}/agent-deployment/app/requirements.txt"
    executable: pip3
  become: yes

- name: Create directory
  file:
    path: "{{ ota_agent_deployment_install_dir }}"
    state: directory
    mode: "0755"
    owner: root
  become: yes

- name: Install app
  copy:
    src: "{{ ota_internal_clone_dir }}/agent-deployment/app"
    dest: "{{ ota_agent_deployment_install_dir }}"
    mode: 0644
  become: yes

- name: Install service
  copy:
    src: "{{ ota_internal_clone_dir }}/agent-deployment/systemd/agent-deployment.service"
    dest: /etc/systemd/system/
    mode: 0755
  become: yes

- name: Enable service
  systemd:
    name: agent-deployment.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: yes
    masked: no
  become: yes
